services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    image: fluent/fluentd:v0.12-debian
    container_name: fluentd
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c 'echo > /dev/tcp/localhost/24224'"]
      interval: 5s
      retries: 5
      start_period: 10s
